### ISSUE TITLE
Data Migration issues - specs & features

### ISSUE THREAD

**Issue by nkarni** [nkarni/bc#21]
1.  Did a product name search and pressed filter "Therapod" and found the following problems:

  a.  Therapod Classic Manual - no specs, no features
  b.  Therapod Linear - No specs and no features
  c.  HD Elegance - specs not in correct format but Features are in correct format
  d.  Therapod Essential Drafting - no information against this product at all
  e.  Therapod Element - no specs, no features
  f.  Therapod Classic Sensor Std - no specs, no features

  Note:  if no specs or features for these products there were meta tag keywords and meta tag descriptions BUT if there were specs and features there were no meta tag keywords or description.

2.  Compact footrest - specs and features are not in correct format - each spec or feature is in a continuous row

3.  HAG Capisco - no specs, no features
4.  HAG Capisco Saddle Seat - no specs, no features

**Comment by maciej-trebacz** [comment]
Therapod Essential Drafting seem to have all the information: http://bcdev.utopiacreative.com/therapod-essential-drafting
